SCALE Job started on Mon 21/01/2019 15:58:46
With Host name smpark-Precision-Tower-3420
working directory /tmp/scale.smpark.30784
and process id 30784.
Input file named /home/smpark/projects/msr-neutronics/MSFR/scale/mc_paper/mc_paper_900.inp
and output file named /home/smpark/projects/msr-neutronics/MSFR/scale/mc_paper/mc_paper_900.out
##########################################################
***Created 4 infinite homogeneous cells from unreferenced mixtures.
>>> Loading SCALE Standard Composition Library from /home/smpark/projects/SCALE-6.2.2/data/scale.rev39.sclib
>>> Loading CE library /home/smpark/projects/SCALE-6.2.2/data/ce_v7.1_endf.xml
***Warning:    The following mixture(s), specified in newt material list,              ***
               *** were not used in the geometry specification:                        ***
               ***    4
