SCALE Job started on Tue 13/11/2018 14:40:38
With Host name smpark-Precision-Tower-3420
working directory /tmp/scale.smpark.335
and process id 335.
Input file named /home/smpark/projects/msr-neutronics/MSFR/scale/msfr-input.i
and output file named /home/smpark/projects/msr-neutronics/MSFR/scale/msfr-input.out
##########################################################
***Created 2 infinite homogeneous cells from unreferenced mixtures.
>>> Loading SCALE Standard Composition Library from /home/smpark/projects/SCALE-6.2.2/data/scale.rev39.sclib
>>> Loading CE library /home/smpark/projects/SCALE-6.2.2/data/ce_v7.1_endf.xml
***Error:        Invalid input - Keywords "read XXXX" not found after title card.  Input cannot be processed.
